---
title: "project_eda"
output: pdf_document
---

```{r data_preprocessing, warnings=FALSE}
library(dplyr)
# lab = read.csv("data/health/labs.csv")
demographics = read.csv("data/health/demographic.csv")
ques = read.csv("data/health/questionnaire.csv")
exam = read.csv("data/health/examination.csv")

# join tables by participant ID
df = inner_join(demographics, ques, by="SEQN")
df = inner_join(df, exam, by="SEQN")
dim(df)

# subset df_adult to consider only the variables we're interested in
response = "BMXWT"
predictors = c("BMXHT", "RIAGENDR", "RIDAGEYR", "RIDRETH3", "DMDEDUC2", "DMDMARTL", "DMDFMSIZ", "INDFMIN2", 
               "ALQ101", "ALQ120Q", 
               "CBD070", "CBD120", "CBD130", 
               "DBD895", "DBD900", "DBQ197", 
               "DPQ020", "DPQ030",
               "PAQ710", 
               "SLD010H", "SMQ040")

columns = c(predictors, response)

df = df[names(df) %in% columns]

# rename columns to more intuitive names
df = rename(df, height = BMXHT, gender = RIAGENDR, age = RIDAGEYR, race = RIDRETH3, edu = DMDEDUC2,
            marriage = DMDMARTL, famsize = DMDFMSIZ, famincome = INDFMIN2,
            alcohol12yr = ALQ101, alcoholfrq = ALQ120Q, grocery = CBD070, eatout = CBD120,
            delivery = CBD130, milk = DBQ197, meals_nothome = DBD895, meals_fastfood = DBD900,
            depressed = DPQ020, sleep_trouble = DPQ030, tv_hrs = PAQ710,
            sleep_hr = SLD010H, smoke = SMQ040, weight = BMXWT)

# subset the df to consider only adults aged 18 or above
df_adult = df[df$age > 20,]

# demographics
df_adult = df_adult[which(df_adult$edu!=7 & df_adult$edu!=9),]
df_adult = df_adult[which(df_adult$marriage!=77 & df_adult$marriage!=99),]
df_adult = df_adult[which(df_adult$famincome!=77 & df_adult$famincome!=99),]

# alcohol use
df_adult = df_adult[which(df_adult$alcohol12yr!=7 & df_adult$alcohol12yr!=9),]
df_adult = df_adult[which(df_adult$alcoholfrq!=777 & df_adult$alcoholfrq!=999),]

# consumer behavior
df_adult = df_adult[which(df_adult$grocery!=777777 & df_adult$grocery!=999999),]
df_adult = df_adult[which(df_adult$eatout!=777777 & df_adult$eatout!=999999),]
df_adult = df_adult[which(df_adult$delivery!=777777 & df_adult$delivery!=999999),]

# diet behavior
df_adult = df_adult[which(df_adult$meals_nothome != 5555 & df_adult$meals_nothome != 7777 & df_adult$meals_nothome != 9999),]
df_adult = df_adult[which(df_adult$meals_fastfood != 5555 & df_adult$meals_fastfood != 7777 & df_adult$meals_fastfood != 9999),]

# physical activity
df_adult$tv_hrs[which(df_adult$tv_hrs == 0)] = 1
df_adult$tv_hrs[which(df_adult$tv_hrs == 8)] = 0
df_adult = df_adult[which(df_adult$tv_hrs != 77 & df_adult$tv_hrs != 99),]

# mental health
df_adult = df_adult[which(df_adult$depressed!=7 & df_adult$depressed!=9),]
df_adult = df_adult[which(df_adult$sleep_trouble!=7 & df_adult$sleep_trouble!=9),]

# sleeping behavior
df_adult = df_adult[which(df_adult$sleep_hr != 99),]

# smoking behavior
df_adult$smoke[which(is.na(df_adult$smoke))] = "missing"

# drop observations where number of missing value in certain columns is < 100
drop_obs = c("famincome", "grocery", "eatout", "delivery", 
             "sleep_hr","depressed", "sleep_trouble", "height", "weight")

for (feature in drop_obs){
  df_adult = df_adult[!is.na(df_adult[feature]),]
}

categorical_features = c("gender", "race", "edu", "marriage",
                         "famincome", "alcohol12yr", "milk", "depressed", 
                         "sleep_trouble", "smoke", "tv_hrs")

numeric_features = c("age", "famsize", "alcoholfrq", "grocery", "eatout",
                     "delivery", "meals_nothome", "meals_fastfood", "sleep_hr")

# convert categorical variables into factors
df_adult[categorical_features] = lapply(df_adult[categorical_features], factor)

apply(df_adult, 2, function(x) sum(is.na(x))) # check how many missing data
sapply(df_adult, class) # check data classes
```

## Exploratory Data Analysis
### Response Variable (BMI)
```{r fig.height=3, fig.width=10, fig.align="center", warning=FALSE}
library(ggplot2)
require(gridExtra)
transform1 = log(df_adult$weight)
transform2 = log(log(df_adult$weight))

# response variable distribution
plot1 = ggplot(df_adult, aes(weight)) +
  geom_histogram() +
  ggtitle("BMI")
plot2 = ggplot(df_adult, aes(transform1)) +
  geom_histogram() +
  ggtitle("Log(BMI)")
plot3 = ggplot(df_adult, aes(transform2)) +
  geom_histogram() +
  ggtitle("Log(Log(BMI))")
grid.arrange(plot1, plot2, plot3, ncol=3)
```

```{r}
df_adult$log.weight = log(df_adult$weight)
```


### Predictor Variables

#### Categorical Variables
```{r fig.height=27, fig.width=15, fig.align="center", warning=FALSE}
plot1 = ggplot(df_adult, aes(x=gender, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Gender", y="log(weight)") + 
  ggtitle("Weight by Gender")
plot2 = ggplot(df_adult, aes(x=race, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Race", y="log(weight)") + 
  ggtitle("Weight by Race")
plot3 = ggplot(df_adult, aes(x=edu, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Education Level", y="log(weight)") + 
  ggtitle("Weight by Education Level")
plot4 = ggplot(df_adult, aes(x=marriage, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Marital Status", y="log(weight)") + 
  ggtitle("Weight by Marital Status")
plot5 = ggplot(df_adult, aes(x=famincome, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Family Income", y="log(weight)") + 
  ggtitle("Weight by Family Income")
plot6 = ggplot(df_adult, aes(x=alcohol12yr, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Alcohol Use", y="log(weight)") + 
  ggtitle("Weight by Alcohol Use")
plot7 = ggplot(df_adult, aes(x=milk, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Milk Consumption", y="log(weight)") + 
  ggtitle("Weight by Milk Consumption")
plot8 = ggplot(df_adult, aes(x=depressed, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Depressed", y="log(weight)") + 
  ggtitle("Weight by Despressed")
plot9 = ggplot(df_adult, aes(x=sleep_trouble, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Alcohol Use", y="log(weight)") + 
  ggtitle("Weight by Sleep Trouble")
plot10 = ggplot(df_adult, aes(x=smoke, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="Smoke", y="log(weight)") + 
  ggtitle("Weight by Smoke")
plot11 = ggplot(df_adult, aes(x=tv_hrs, y = log.weight)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  labs(x="TV Consumption", y="log(weight)") + 
  ggtitle("Weight by TV Consumption")
grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, plot11, ncol=2)
```

#### Numeric Variables
Distribtuion of numeric variables
```{r fig.height=9, fig.width=10, fig.align="center", warning=FALSE}
# numeric predictor variable distributions
plot1 = ggplot(df_adult, aes(age)) + geom_histogram() +
  ggtitle("Age")
plot2 = ggplot(df_adult, aes(height)) + geom_histogram() +
  ggtitle("Height")
plot3 = ggplot(df_adult, aes(famsize)) + geom_histogram() +
  ggtitle("Family Size")
plot4 = ggplot(df_adult, aes(alcoholfrq)) + geom_histogram() +
  ggtitle("Frequency of Alcohol Consumption")
plot5 = ggplot(df_adult, aes(grocery)) + geom_histogram() +
  ggtitle("Money Spent on Grocery")
plot6 = ggplot(df_adult, aes(eatout)) + geom_histogram() +
  ggtitle("Money Spent Eating Out")
plot7 = ggplot(df_adult, aes(delivery)) + geom_histogram() +
  ggtitle("Money Spent on Delivered Food")
plot8 = ggplot(df_adult, aes(meals_nothome)) + geom_histogram() +
  ggtitle("Number of Meals Not Home Prepared")
plot9 = ggplot(df_adult, aes(meals_fastfood)) + geom_histogram() +
  ggtitle("Number of Fast Food Meals")
plot10 = ggplot(df_adult, aes(sleep_hr)) + geom_histogram() +
  ggtitle("Hours of Sleep")
grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, ncol=2)
```                    
          
Response vs. numeric distribution
```{r fig.height=9, fig.width=10, fig.align="center", warning=FALSE}
df_adult$log.alcoholfrq = log(df_adult$alcoholfrq + 1)
df_adult$log.grocery = log(df_adult$grocery + 1)
df_adult$log.eatout = log(df_adult$eatout + 1)
df_adult$log.delivery = log(df_adult$delivery + 1)
df_adult$log.nothome = log(df_adult$meals_nothome + 1)
df_adult$log.fastfood = log(df_adult$meals_fastfood + 1)

# numeric predictor variable distributions
plot1 = ggplot(df_adult, aes(x=age, y=log.weight)) + geom_point() + 
  ggtitle("Age")
plot2 = ggplot(df_adult, aes(x=height, y=log.weight)) + geom_point() + 
  ggtitle("Height")
plot3 = ggplot(df_adult, aes(x=famsize, y=log.weight)) + geom_point() + 
  ggtitle("Family Size")
plot4 = ggplot(df_adult, aes(x=alcoholfrq, y=log.weight)) + geom_point() + 
  ggtitle("Frequency of Alcohol Consumption")
plot5 = ggplot(df_adult, aes(x=grocery, y=log.weight)) + geom_point() + 
  ggtitle("Money Spent on Grocery")
plot6 =ggplot(df_adult, aes(x=eatout, y=log.weight)) + geom_point() + 
  ggtitle("Money Spent Eating Out")
plot7 = ggplot(df_adult, aes(x=delivery, y=log.weight)) + geom_point() + 
  ggtitle("Money Spent on Delivered Food")
plot8 =ggplot(df_adult, aes(x=meals_nothome, y=log.weight)) + geom_point() + 
  ggtitle("Number of Meals Not Home Prepared")
plot9 = ggplot(df_adult, aes(x=meals_fastfood, y=log.weight)) + geom_point() + 
  ggtitle("Number of Fast Food Meals")
plot10 = ggplot(df_adult, aes(x=sleep_hr, y=log.weight)) + geom_point() + 
  ggtitle("Hours of Sleep")
grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, ncol=2)
```          


color by some factor

```{r fig.height=12, fig.width=15, fig.align="center", warning=FALSE}
# numeric predictor variable distributions
plot1 = ggplot(df_adult, aes(x=age, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Age")
plot2 = ggplot(df_adult, aes(x=height, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Height")
plot3 = ggplot(df_adult, aes(x=famsize, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Family Size")
plot4 = ggplot(df_adult, aes(x=alcoholfrq, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Frequency of Alcohol Consumption")
plot5 = ggplot(df_adult, aes(x=grocery, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Money Spent on Grocery")
plot6 =ggplot(df_adult, aes(x=eatout, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Money Spent Eating Out")
plot7 = ggplot(df_adult, aes(x=delivery, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Money Spent on Delivered Food")
plot8 =ggplot(df_adult, aes(x=meals_nothome, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Number of Meals Not Home Prepared")
plot9 = ggplot(df_adult, aes(x=meals_fastfood, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Number of Fast Food Meals")
plot10 = ggplot(df_adult, aes(x=sleep_hr, y=log.weight, colour=gender)) + geom_point() + 
  ggtitle("Hours of Sleep")
grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, plot9, plot10, ncol=2)
```          


parallel corrd plot to figure out if interaction may be helpful
```{r fig.height=5, fig.width=10, fig.align="center", warning=FALSE}
# library(MASS)
# library(RColorBrewer)
# k <- adjustcolor(brewer.pal(5, "Set2")[df_adult$sleep_trouble], alpha=.6)
# predictor = c("sleep_hr", "age", "log.delivery", "meals_nothome", "meals_fastfood")
# parcoord(df_adult[,predictor], col=k)
```

```{r}
df_adult
```
```{r}
#model 1 with all main effects
model1 = lm(log.weight~gender+age+race+edu+marriage+famsize+famincome+alcohol12yr+log.alcoholfrq+log.grocery+log.eatout+log.delivery+milk+log.nothome+log.fastfood+depressed+sleep_trouble+tv_hrs+sleep_hr+smoke+height, data = df_adult)
summary(model1)
extractAIC(model1)
```
```{r}
plot(predict(model1), resid(model1))
abline(0,0)
hist(resid(model1))
```
```{r}
diagnostic.plots = function(model)
{
  resid = data.frame(resid = model$residuals)
  
  # calculate qq line
  y = quantile(resid$resid, c(0.25, 0.75)) # Find the 1st and 3rd quartiles
  x = qnorm( c(0.25, 0.75))          # Find the matching normal values on the x-axis
  slope = diff(y) / diff(x)          # Compute the line slope
  int = y[1] - slope * x[1]          # Compute the line intercept
  
  # qq plot
  qq.plot = ggplot(resid, aes(sample = resid)) +
    stat_qq() +
    geom_abline(intercept = int, slope = slope)
  
  
  # Fitted values vs residuals to check equal variance
  var.plot = ggplot(model, aes(.fitted, sqrt(abs(.stdresid)))) + 
      geom_point(na.rm = TRUE) + 
      stat_smooth(method = "loess", na.rm = TRUE) + 
      xlab("Fitted Value") + 
      ylab(expression(sqrt("|Standardized residuals|"))) +
      ggtitle("Scale-Location") +
      theme_bw()
  
  grid.arrange(qq.plot, var.plot)
}
diagnostic.plots(model1)
```


```{r}
#model 2 with all the interaction terms
model2 = lm(log.weight~(gender+age+race+edu+marriage+famsize+famincome+alcohol12yr+log.alcoholfrq+log.grocery+log.eatout+log.delivery+milk+log.nothome+log.fastfood+depressed+sleep_trouble+tv_hrs+sleep_hr+smoke+height)^2, data = df_adult)
summary(model2)
extractAIC(model2)
```

```{r}
#forward selection from intercept only
model3 = step(lm(log.weight~1, data = df_adult), scope = list(upper = model2), direction = "forward", trace = 0)
summary(model3)
extractAIC(model3)
```
```{r}
extractAIC(model1)
extractAIC(model2)
extractAIC(model3)
```
```{r warning=FALSE}
library(caret)
set.seed(12345)
nsims=500
n=nrow(df_adult)
sse1 = rep(NA,nsims)
n.train = 1500
for(i in 1:nsims){
  
  categorical_partition = paste(df_adult$marriage, df_adult$race, df_adult$gender,df_adult$famincome,
                                df_adult$edu, df_adult$alcohol12yr, df_adult$milk, df_adult$smoke,
                                df_adult$tv_hrs, df_adult$sleep_trouble, df_adult$depressed)
  reorder= createDataPartition(categorical_partition, times = 1, p = 0.5, list = FALSE)

  train=df_adult[reorder,]
  test=df_adult[-reorder,]
  
  ###fit1: result of model 1
  fit1=lm(log.weight ~ gender + race + tv_hrs + smoke + edu + 
    age + marriage + milk + depressed + meals_nothome + alcoholfrq + 
    meals_fastfood + gender:smoke + gender:race + age:marriage + 
    smoke:marriage + smoke:depressed + age:meals_nothome + gender:edu + 
    gender:meals_nothome + race:meals_fastfood + age:meals_fastfood ,data=train)

  
  sse1[i]=sum((test$log.weight-predict(fit1,new=test))^2)


}

c(mean(sse1))
```

